DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  status BOOLEAN NOT NULL,
  info VARCHAR(255) NOT NULL
);
