DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  title VARCHAR(225) NOT NULL,
  category VARCHAR(225) NOT NULL,
  status BOOLEAN NOT NULL,
  info VARCHAR(225) NOT NULL,
  user_id INTEGER NOT NULL REFERENCES user(id)
);
